#!/bin/bash
set -eu
LATEST_RELEASE=$(curl -s https://api.github.com/repos/cli/cli/releases/latest)
VERSION=$(echo $LATEST_RELEASE | jq -r '.tag_name')
DEB_URL=$(echo $LATEST_RELEASE | jq -r '.assets[].browser_download_url | select(. | contains("linux_amd64.deb"))')

EXISTING_VERSION="v$(gh version | head -n1 | cut -d ' ' -f3)"
if [[ "$EXISTING_VERSION" == "$VERSION" ]]; then echo "Already on latest version $VERSION."; exit 0; fi

read -p "Press [Enter] to update gh to version $VERSION"

wget --quiet -O gh_latest.deb $DEB_URL
sudo dpkg -i gh_latest.deb
rm gh_latest.deb
gh --version
